accumulate_grad_batches: 1
acous_params:
- - 480
  - 1200
  - 80
- - 240
  - 1200
  - 160
amp: false
asr_percep_ckpt: ''
asr_percep_loss_layer: 4
audio_num_mel_bins: 160
audio_sample_rate: 24000
base_config:
- ./megatts.yaml
batch_by_size: true
binarization_args:
  shuffle: false
  trim_eos_bos: false
  with_align: true
  with_bert: false
  with_denoised: false
  with_f0: false
  with_f0cwt: false
  with_linear: false
  with_mel: false
  with_spk_embed: false
  with_w2v_token: false
binarizer_cls: data_gen.tts.base_binarizer.BaseBinarizer
binary_data_dir: data/binary_v3/sa_data_v1
c_spk_enc: 512
char_dict_size: 15000
chunked_read: true
clip_grad_norm: 1
clip_grad_value: 0
conv_use_pos: false
copy_meta_from: data/binary/megadb231119
ddp_dir: ''
debug: false
dec0_dilations:
- 1
- 2
- 4
- 1
- 2
- 4
- 1
dec0_kernel_size: 3
dec_dilations:
- 1
- 2
- 1
- 2
- 1
dec_ffn_kernel_size: 9
dec_inp_add_noise: false
dec_kernel_size: 5
dec_layers: 4
dec_post_net_kernel: 3
decoder_rnn_dim: 0
decoder_type: conv
disc_gp_interval: 0
disc_hidden_size: 32
disc_hidden_size_max: 128
disc_interval: 1
disc_kernel: 3
disc_loss_type: LSGAN
disc_lr: 0.0001
disc_mel_cond: true
disc_norm_type: sn
disc_num_layers: 3
disc_rerun_gen: false
disc_start_steps: 0
disc_time_len: -1
disc_type: patchgan_2d
disc_warmup: 100
discriminator_grad_norm: 1
discriminator_optimizer_params:
  eps: 1.0e-06
  weight_decay: 0.0
dropout: 0.0
ds_add_pitch_embed: false
ds_workers: 4
dur_alpha: 1.0
dur_context_enc: true
dur_log: true
dur_predictor_kernel: 3
dur_predictor_layers: 2
dur_use_char: true
dur_use_spk: true
enc_dec_norm: ln
enc_dilations:
- 1
- 1
- 1
- 1
enc_ffn_kernel_size: 5
enc_kernel_size: 5
enc_layers: 8
enc_post_net_kernel: 3
enc_pre_ln: true
enc_prenet: true
encoder_K: 8
encoder_type: rel_fft
endless_ds: true
eval_max_batches: 0
exclude_spk:
- SA_BV408
exp_name: 1106_megatts3_dit_small_fsdp_stride4
f0_max: 600
f0_min: 60
fast_ds: true
ffn_act: gelu
ffn_hidden_size: 1024
fft_size: 1200
fg_spk_enc_hidden: 256
fmax: 12000
fmin: 0
force_denoise: false
frames_multiple: 8
gen_dir_name: ''
glat_size: 128
griffin_lim_iters: 30
hdfs_path_replace:
  data/binary_v3: hdfs://haruna/home/byte_arnold_lq_speech_tts/user/renyi/data/binary_v3_sorted
hidden_size: 512
hop_size: 240
ignore_begin_end_sil: false
infer: false
infer_sil_env: false
infer_spk_name: ''
init_method: tcp
keep_c0_init: true
kl_min: 0
kl_start_steps: 1
kmeans_every: 10000
kmeans_repeat: false
lambda_energy: 0.1
lambda_f0: 1.0
lambda_fm: 0.0
lambda_kl: 1.0
lambda_mel_adv: 0.05
lambda_ph_dur: 1.0
lambda_sent_dur: 0.0
lambda_uv: 1.0
lambda_word_dur: 0.0
lat_for_dur: false
latent_dim: 16
latent_size: 256
layers_in_block: 2
ling_label_dict_size:
- 20
- 4
- 5
- 2
- 3
- 3
- 3
- 6
- 15
ling_labels:
- tone
load_ckpt: ''
loud_norm: false
lr: 5.0e-05
mask_r: 0.9
master_addr: ''
max_epochs: 1000
max_frames: 12000
max_input_tokens: 1550
max_sentences: 40
max_timbre_len: 1000
max_tokens: 30000
max_updates: 4000000
max_valid_sentences: 1
max_valid_tokens: 60000
mel_losses: pitch_percep|l1|ssim
mel_vmax: 0.5
mel_vmin: -6
min_frames: 50
min_spk_items: 5
mix_melout_timbre: true
mix_ph_timbre: false
mixed_precision: bf16
model_type: 1
multistage: false
nVQ: 256
no_text_enc: false
not_save_modules:
- pitch_precep_model
- asr_percep_model
- tone_precep_model
num_ckpt_keep: 5
num_heads: 2
num_sanity_val_steps: 5
num_spk: 50000
num_valid_plots: 10
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.999
out_wav_norm: true
pad_frames: false
perturb_ref_mel: false
pitch_extractor: reaper
pitch_key: pitch
pitch_percep_ckpt: checkpoints/1120_sa_ws_gs_pitchpdt_singlec
pitch_percep_loss_layer: -1
pitch_type: frame
plot_mels: true
precision: fp16
predict_pitch: false
predictor_dropout: 0.0
predictor_grad: 1.0
predictor_hidden: -1
predictor_kernel: 5
predictor_layers: 5
preprocess_args:
  add_eos_bos: true
  mfa_group_shuffle: false
  mfa_offset: 0.02
  mfa_use_tone: true
  nsample_per_mfa_group: 1000
  reset_phone_dict: true
  reset_word_dict: true
  save_sil_mask: true
  txt_processor: en
  use_mfa: true
  vad_max_silence_length: 12
  wav_processors: []
  with_phsep: true
preprocess_cls: ''
print_nan_grads: true
prior_flow:
  hidden_size: 256
  kernel_size: 3
  n_blocks: 4
  n_layers: 6
  nn_type: conv
  word_conder_layers: 0
processed_data_dir: ''
profile_infer: false
raw_data_dir: ''
reduce_cvq_embed: true
reduce_transient_noise: false
ref_mel_bins: 160
ref_size_max: 2000
ref_size_min: 1000
rename_tmux: true
resume_from_checkpoint: 0
save_best: false
save_codes: []
save_f0: false
save_f0_mels: false
save_gt: true
scheduler: warmup
seed: 1234
shuffle_ref: false
speakers:
- .*
split_ref: true
stage2_use_lat: false
start_rank: -1
task_cls: tasks.tts.megatts3_cfm.MegaTTSCFMTask
tb_log_interval: 100
temperature: 0.8
test_dataset: false
test_emo_id: 0
test_ids: []
test_max_batches: 100
test_set_name: test
test_speakers: []
tgt_size_max: 1200
tgt_size_min: 400
tone_percep_ckpt: ''
train_max_batches_epoch: 4000
train_set_name: train
train_sets:
- data/binary_v3/sa_data_v1
- data/binary_v3/sami_data_v1
- data/binary_v3/small_sets_v1
- data/binary_v3/audible_v1
- data/binary_v3/evelabs_v1
- data/binary_v3/film_v1
- data/binary_v3/gigaspeech_v1
- data/binary_v3/libriheavy_v1
- data/binary_v3/xmly_v1
- data/binary_v3/pirbay_v1
- data/binary_v3/dt_child_v1
- data/binary_v3/sami_inhouse202310_v1
- data/binary_v3/audiobook_v1
- data/binary_v3/changting202310_v1
- data/binary_v3/changting_v1
- data/binary_v3/ytb_v1
- data/binary_v3/resso_v1
- data/binary_v3/xyz_v1
- data/binary_v3/wenetspeech_v1
- hdfs://haruna/home/byte_arnold_lq_speech_tts/user/renyi/data/binary_v3_sorted/sa_data_231215_v1
train_spk_embed_only: false
use_bert_input: false
use_cfg: true
use_char: true
use_cond_disc: false
use_cur_global: false
use_cur_global_dec: true
use_dur_embed: true
use_dur_mask_embed: true
use_ema: false
use_env_modeling: false
use_expand_ph: true
use_file_system_mp: true
use_finegrained_spk: false
use_fork: false
use_fsdp: true
use_global_lat: false
use_gt_dur: false
use_gt_f0: false
use_gt_latent: true
use_hdfs_dataset: true
use_mix_spk_embed: false
use_multisent_training: true
use_new_vae: false
use_ph_level_f0: false
use_ph_pos_embed: true
use_pitch_embed: false
use_pitch_embed_dec: false
use_pitch_pred: true
use_pos_embed: true
use_prior_flow: true
use_qk_norm: true
use_random_spk_embed: false
use_seq_cfg: true
use_spk_embed: false
use_spk_enc: true
use_spk_id: false
use_uv: true
use_vae: true
use_vpcfm: true
use_vqvae: true
use_w2v_input: false
use_word_encoder: true
use_word_input: false
vae_dur_grad: 0.1
vae_enc_hidden_size: 384
vae_path: ./checkpoints/1009_sdvae_lat24_stride4_left_pad_ema2_fix
vae_ph_conder_layers: 0
vae_share_spk_embed: false
vae_stride: 4
vae_word_conder_layers: 0
val_check_interval: 2000
val_max_batches: 100
val_train_overlap: false
valid_infer_interval: 4000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_set_name: valid
validate: false
vocoder: samelgan
vocoder_ckpt: checkpoints/1117_melgan-nsf_full_1
vocoder_use_predict_pitch: false
vq_stride: 8
vqvae_start_steps: 0
w2v_type: hb
wandb: false
warmup_updates: 10000
weight_decay: 0
win_size: 1200
word_dict_size: 10000
work_dir: checkpoints/1106_megatts3_dit_small_fsdp_stride4
world_size: -1
z_channels: 64
z_clamp: 2.0
