base_config:
- egs/tts/config_base.yaml
- egs/tts/datasets/swan_base_dataset.yaml

# task
# task_cls: tasks.tts.swan_dump_task.SwanDiTTask
task_cls: tasks.tts.swan_task.SwanDiTTask

# audio
fft_size: 2400
hop_size: 480
win_size: 2400
audio_sample_rate: 48000
f0_max: 600
f0_min: 60
fmax: 24000
fmin: 0

# data
frames_multiple: 4
dataset_cls: tasks.tts.dataset_utils.swan_base_fastdataset.SwanTTSShmDataset
val_dataset_cls: tasks.tts.dataset_utils.tts_datasets.DiTWavTextDataset
use_audio_dataset: False

# dataloader
eval_max_batches: 0
ds_workers: 6
max_tokens: 10000
max_sentences: 200
max_frames: 12000   # 5min
min_frames: 100
tgt_size_max: 6000
tgt_size_min: 100
fast_ds_prefetch_steps: 2

online_text_alignment_task: False
online_text_alignment: False
online_text_alignment_batch_size: 32
online_text_alignment_work_dir: user/service_cache/asr

pipeline_cache_future: False
pipeline_prefetch_aligner: True
pipeline_prefetch_vae: True

shuffle_spk_ids: False

# model
model_size: 2b
use_cosyvoice2_text_tokenizer: True
mix_text_pinyin:
  enable: true
  enable_prob: 0.4
use_spk_mask: False
use_gated_attention: False
use_dynamic_cross_gate: True
encoder_ffn_mult: 4.0
drop_ref_wav: 0.5

# caption encoder
use_caption: False
caption_encoder_dim: 4096
use_caption_text_mark: True

latent_dim: 64
vae_stride: 4
vae_ckpt: checkpoints/260303_vae_v9m2_48k_25hz_z64/model_ckpt_steps_178000_model_gen.ckpt
latent_norm_mode: per_channel
vae_encode_chunk_sec: 120
vae_encode_max_batch_size: 32
vae_deterministic: False

load_ckpt: ''
use_fsdp: true
sharding_strategy: hybrid
gradient_checkpointing: false

use_ema: False
ema_decay: 0.9999

# training
optimizer:
  betas:
  - 0.9
  - 0.999
  fused: false
  lr: 8.0e-5
  weight_decay: 0.01
scheduler_lr_min: 5.0e-5
ckpt_milestone_interval: 50000
tb_log_interval: 1
grad_norm_skip_warmup_steps: 10000
grad_norm_skip_threshold: 10
grad_norm_skip_warmup_log_enabled: False
