base_config:
  - ./hifigan_config.yaml
  - ./config_base.yaml
  - ./datasets/vae_dataset.yaml

# dataset
# dataset_cls: tasks.tts.dataset_utils.megatts_fastdataset.DiTWavShmDataset
# val_dataset_cls: tasks.tts.dataset_utils.tts_datasets.DiTWavDataset
# processer_fn: tasks.tts.dataset_utils.megatts_fastdataset.processer_fn_dit_wav
# build_fast_dataloader: tasks.tts.dataset_utils.megatts_fastdataset.build_fast_dataloader
dataset_cls: tasks.tts.dataset_utils.vae_fastdataset.VAEShmDataset
val_dataset_cls: tasks.tts.dataset_utils.tts_datasets.DiTWavTextDataset
dataloader_mp_type: fork
masked_audio_value: 0
max_samples: 72000

ds_workers: 6 
max_sentences: 50
max_frames: 12000
min_frames: 50
frames_multiple: 8
vae_stride: 4
chunk_size: 24000


# optimizer
optimizer:
  betas:
  - 0.9
  - 0.999
  fused: false
  lr: 7.5e-5
  weight_decay: 0.00
lr: 1.0e-4

# task
nkp: 103
task_cls: tasks.tts.wavvae3.WavVAETask
use_fsdp: false
load_ckpt: ''
pretrained: ''
max_tokens: 1000
use_ema: false
val_check_interval: 2000
val_batch_size: 0
eval_max_batches: 0
infer_steps: 100
fast_ds_shuffle_buffer: 128
num_workers: 16

freeze_encoder: True