# task
binary_data_dir: ''
work_dir: '' # experiment directory.
infer: false # infer
amp: false
mixed_precision: bf16
seed: 42
dataloader_seed: 1231
debug: false
save_codes: ['tasks', 'modules', 'egs', 'utils']
num_workers: 16

#############
# dataset
#############
ds_workers: 1
test_num: 100
endless_ds: true
sort_by_len: true
fast_ds_prefetch_steps: 8
fast_ds: true
dataloader_mp_type: fork

#########
# train
#########
print_nan_grads: true
load_ckpt: ''
save_best: false
num_ckpt_keep: 5
clip_grad_norm: 0
accumulate_grad_batches: 1
tb_log_interval: 100
log_grad_every_n_steps: 1
grad_norm_skip_threshold: 10000.0
grad_norm_skip_init_threshold: 10000.0
grad_norm_skip_warmup_steps: 100
grad_norm_skip_warmup_log_enabled: True
max_epochs: 1000
max_updates: 2000000
max_tokens: 40000
max_sentences: 100000
resume_from_checkpoint: 0
rename_tmux: false
prefetch_factor: 2
infer_save_dir: ''
use_fsdp: false
ckpt_milestone_interval: 100000
load_map_to_gpu: false
mmap: true
start_rank: -1
world_size: -1
torch_compile: false
sharding_strategy: hybrid

#########
# eval
#########
num_sanity_val_steps: 10  # steps of validation at the beginning
check_val_every_n_epoch: 10
val_check_interval: 2000
valid_monitor_key: 'val_loss'
valid_monitor_mode: 'min'
max_valid_tokens: -1
max_valid_sentences: -1
rename: -1
test_max_batches: -1
