# basic
work_dir: user/reward_cache

# server
n_devices: 7
workers_per_device: 3
daemon: True

# polling
poll_interval: 0.5  # seconds

# reward
reward:
  qwen3aligner: False
  phone: True

# monitor
stats_interval: 60  # seconds

