base_config:
  - egs/egs_bases/config_base.yaml
  - ../dataset_params.yaml
binarization_args:
  with_spk_embed: false
  with_align: false

train_set_name: 'train'
train_sets: []
valid_set_name: 'test'
test_set_name: 'test'
nsf_type: 'none'
generator_grad_norm: 10.0    # Generator's gradient norm.
discriminator_grad_norm: 1.0 # Discriminator's gradient norm.

use_pitch_embed: false
use_fm_loss: false
use_ms_stft: false
use_cond_disc: false

###########
# train and eval
###########
max_samples: 24000
max_sentences: 4
max_valid_sentences: 1
max_updates: 2000000
val_check_interval: 5000
valid_infer_interval: 50000
val_max_batches: 100
filedataset_path: ''