base_config: ./hifigan.yaml
task_cls: tasks.vocoder.sa_melgan.SAMelGANTask
melgan_config:
  "n_mel_channels": 160
  "n_residual_layers": 4
  "ndf": 16
  "num_D": 3
  "n_layers_D": 4
  "downsamp_factor": 4
  "lambda_feat": 0.0
  "cond_disc": false
  "batch_size": 8
  "seq_len": 100
  "epochs": 1000
  "log_interval": 100
  "save_interval": 5000
  "n_test_samples": 5
  "sampling_rate": 24000
  "num_band": 1
  "pretrain_steps": 0
  "multi_resolution": 0
  "frame_shift": 240
  "load_D": 1
  "up_sample": [
    5,
    4,
    4,
    3,
  ]
  "use_lsgan": 1
  "sub_dis": 1
  "run_hdfs": 0
  "offset": 0
  "single_stft": 0
  "use_interpolate": 0
  "use_time_loss": 1
  "use_mel_loss": 1
  "use_F_dis": 0
  "use_sbd": 0
  "use_melnorm": 0
  "lr": 0.0005
  "num_workers": 0
  "use_pitch_condition": 1
  "dim_pitch_condition": 1
  "mode_pitch_condition": "singgan_torch"
  "use_aug_pitch": 0
  "backbone_resampling": "librosa_kaiser_best"
  "use_msg_gan": 0
  "use_pitch_prediction": 1
  "use_speaker_prediction": 0
  "tf_start_step": 0
  "tf_end_step": 0
  "tf_start_ratio": 0.0
  "tf_end_ratio": 0.0
  "lambda_log_pitch": 0.4
  "lambda_voiced": 1.0
  "loss_pitch": 1.0
  "loss_speaker": 1.0
  "loss_stft": 0.0
  "tf": 1
  "noise_index": 1.0
  "nr": 0
  use_tanh: true
  res_layers: 1
  all_noise: false
ngf: 24
adam_b1: 0.8
adam_b2: 0.99
lr: 0.0001
disc_lr: 0.0001
