base_config:
  - egs/vae/wavvae_v9.yaml

fft_size: 2400
hop_size: 480
win_size: 2400
audio_sample_rate: 48000
f0_max: 600
f0_min: 60
fmax: 24000
fmin: 0
loud_norm: false
audio_num_mel_bins: 320
mel_vmax: 0.5
mel_vmin: -6

ds_workers: 16
tgt_size_min: 50
tgt_size_max: 1200
frames_multiple: 4
vae_stride: 4
max_tokens: 1200   # mel frames

lr: 1.0e-4
disc_start_steps: 10000

# model
is_vocoder: False
kernel_size: 7
encoder_dim: 16
encoder_rates: [3, 4, 4, 5, 8]
transformer_n_layers: 4
transformer_n_head: 16
transformer_n_kv_heads: 8
transformer_use_sliding_window: True
transformer_sliding_window_size: 32
latent_dim: 64
latent_upsample: 4
decoder_input_dim: 160
decoder_dim: 1920
decoder_rates: [5, 4, 3, 2, 2, 2]

kl_start_steps: 0
kl_annealing_step: 500
warmup_updates: 2000
accumulate_grad_batches: 1
grad_norm_skip_threshold: 5000000.0
grad_norm_skip_init_threshold: 500000.0
freeze_decoder: False
distill_max_steps: 0
low_sample_rate_enhance_prob: 0.1
low_sample_rate: [8000, 11025, 16000, 22050, 24000, 32000, 44100]
gradient_checkpointing: True
cudnn_benchmark: False

lambda_kl: 0.005
lambda_adv: 2.0
lambda_cdisc: 4.0
lambda_mel: 10.0
lambda_stft: 10.0
lambda_mpd: 1.0
lambda_mpd_fm: 1.0
lambda_mrd: 1.0
lambda_mrd_fm: 1.0
lambda_msd: 1.0
lambda_msd_fm: 1.0
lambda_distill: 0.0
lambda_energy: 10.0

load_ckpt_disc: 

use_mr_mel: True
mr_mel:
  fft_size: [32, 64, 128, 256, 512, 1024, 2048, 4096]
  audio_num_mel_bins: [5, 10, 20, 40, 80, 160, 320, 640]
  hop_size: [8, 16, 32, 64, 128, 256, 512, 1024]
  win_size: [32, 64, 128, 256, 512, 1024, 2048, 4096]
  fmin: [0, 0, 0, 0, 0, 0, 0, 0]
  fmax: [24000, 24000, 24000, 24000, 24000, 24000, 24000, 24000]
mel_band_edges_hz: [0.0, 3000.0, 8000.0, 12000.0, 24000.0]
mel_band_weights: [1.0, 1.0, 1.5, 1.5]

stft_loss_params:
  resolutions:
    - [256, 32, 128]
    - [512, 64, 256]
    - [1024, 120, 600]
    - [2048, 240, 1200]


mpd:
  kernel_size: 7
  lReLU_slope: 0.2
  periods:
  - 2
  - 3
  - 5
  - 7
  - 11
  stride: 3
  use_spectral_norm: false
mrd:
  lReLU_slope: 0.2
  resolutions:
  - [256, 24, 96]
  - [512, 50, 240]
  - [1024, 120, 600]
  - [2048, 240, 1200]
  use_spectral_norm: false
use_cond_disc: false
use_mrd: true
use_ms_stft: true
adam_b1: 0.8
adam_b2: 0.95
avg_disc_loss: True
