base_config:
- egs/tts/config_base.yaml
- egs/tts/datasets/tts_posttrain_dataset_v2_simple_260104.yaml

# task
task_cls: tasks.tts.posttrain.prompt_nft_task.PromptTTSPostTrainMultiRewardTask

# data
frames_multiple: 8
dataset_cls: tasks.tts.posttrain.posttrain_fastdataset_v2_simple.PosttrainTTSRepeatShmDataset
val_dataset_cls: tasks.tts.dataset_utils.tts_datasets.DiTWavTextDataset
use_audio_dataset: False

# dataloader
prefetch_steps: 12
eval_max_batches: 0
ds_workers: 4
max_tokens: 12000
max_sentences: 200
max_frames: 6000   # 1min
min_frames: 100
tgt_size_max: 6000  # 60 sec
tgt_size_min: 100   # 4 sec

# model
model_size: goku_2_large
latent_dim: 32
vae_stride: 4
vae_ckpt: checkpoints/251120_wavvae_v4_unfreeze 
audio_tokenizer: glm4v

load_ckpt: ''
use_fsdp: true
sharding_strategy: hybrid
gradient_checkpointing: False

# training
is_posttrain: True
scheduler_lr_min: 4.0e-5
drop_st: True
drop_xt: False # drop x_txt
dit_version: 5 # 1:normal 2:crass_att 3:ph
drop_ref_wav: 0.5
add_vad_mask: False
caption_encoder_dim: 5120

use_caption: False
use_caption_text_mark: False
use_qk_norm: True
use_dynamic_cross_gate: True

use_cosyvoice2_text_tokenizer: True
mix_text_pinyin:
  enable: False
  enable_prob: 0.4
use_spk_mask: True
crossattn_n_layers: 32
use_gated_attention: False

reward_work_dir: user/reward_cache

sample:
  train_batch_size: 16   # num of unique samples per gpu
  num_generation_per_prompt: 2  # each prompt generates N samples
  rollout_micro_batch_size: 4
  num_steps: 40
  guidance_scale: [1.4, 3.0]
per_prompt_stat_tracking: True
dataloader_num_replica: 8   # multi gpu share data

train:
  batch_size: 2
  gradient_accumulation_steps: 4
  num_inner_epochs: 1
  timestep_fraction: 1.0
  timestep_range: [0.0, 0.95]  # fraction, ordered range
  beta: 0.0001
  adv_clip_max: 1
  adv_mode: all
decay_type: 4
nft_beta: 0.1

reward:
  gemini3pro: False
  phone: False
  mos: False
  stoi: False
  pesq: False
  sim: False
  lai: False
  qwen3aligner: False

reward_eval:
  enable: false
  interval: 5
  num_batches: 2
  num_generation_per_prompt: 4
  rollout_micro_batch_size: 8

amp: false
val_check_interval: 1
ckpt_milestone_interval: 10

optimizer:
  betas:
  - 0.9
  - 0.999
  fused: false
  lr: 1.0e-5
  weight_decay: 1.0e-4

pkill_at_end: False
